repos:
- hooks:
  - id: poetry-check
  - id: poetry-lock
  - args:
    - -f
    - requirements.txt
    - --without-hashes
    - -o
    - requirements.txt
    id: poetry-export
  repo: https://github.com/python-poetry/poetry
  rev: 1.5.0
- hooks:
  - entry: bash -c 'make runTests'
    id: tox
    language: system
    name: tox test
    pass_filenames: false
  - entry: bash -c 'make runDocs'
    id: docs
    language: system
    name: mkdocs
    pass_filenames: false
  repo: local
- hooks:
  - id: check-ast
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - args:
    - --autofix
    id: pretty-format-json
  - id: check-merge-conflict
  - exclude: tests/media/.+
    id: check-added-large-files
  - id: detect-private-key
  - id: check-case-conflict
  - id: check-symlinks
  - id: check-executables-have-shebangs
  - id: check-shebang-scripts-are-executable
  - id: mixed-line-ending
  - args:
    - --markdown-linebreak-ext=md
    id: trailing-whitespace
  - exclude: requirements.txt
    id: end-of-file-fixer
  - id: check-builtin-literals
  - id: check-docstring-first
  - id: debug-statements
  - id: fix-byte-order-marker
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
- hooks:
  - id: black
  repo: https://github.com/psf/black
  rev: 23.3.0
- hooks:
  - id: ruff
  repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: v0.0.269
- hooks:
  - entry: bash -c 'mypy --install-types --non-interactive "$@"'
    id: mypy
  repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.3.0
- hooks:
  - id: vulture
  repo: https://github.com/jendrikseipp/vulture
  rev: v2.7
- hooks:
  - args:
    - --autofix
    id: pretty-format-ini
  - args:
    - --autofix
    id: pretty-format-toml
  - args:
    - --autofix
    id: pretty-format-yaml
  repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.9.0
- hooks:
  - additional_dependencies:
    - tomli
    id: codespell
  repo: https://github.com/codespell-project/codespell
  rev: v2.2.4
- hooks:
  - id: shellcheck
  repo: https://github.com/shellcheck-py/shellcheck-py
  rev: v0.9.0.2
- hooks:
  - id: commitizen
  repo: https://github.com/commitizen-tools/commitizen
  rev: 3.2.2
